### ISSUE TITLE
Calculation of keyboard height isn't very reliable

### ISSUE THREAD

**Issue by planetexpress69** [planetexpress69/MKInputBoxView#1]
Get keyboard height from API out of the Notification:
CGSize kbSize = [[info objectForKey:UIKeyboardFrameBeginUserInfoKey] CGRectValue].size;

**Comment by davecom** [comment]
If you mean that MKInputBoxView is sometimes obscured by the keyboard, then I'm seeing that too.
![img_2863](https://cloud.githubusercontent.com/assets/424688/6650004/91b57214-c9d2-11e4-84bf-0f7d6204c843.PNG)
