### ISSUE TITLE
Resetting message title in another method doesn't work

### ISSUE THREAD

**Issue by Horray** [planetexpress69/MKInputBoxView#5]
I tried resetting the title and message in a later method than the initial one I initialized and showed the alertView. When I do that, nothing happens. The alertView's message and title stays the same.

**Comment by planetexpress69** [comment]
Hi there!

Not sure what you're trying to achieve. Could you send some code along with your actual expectations?

Regards,
Martin

**Comment by Horray** [comment]
Thanks for responding!!

I got it. I had to do 2 things.
1. Insert messageLabel in the interface.
2. Then in the method of "- (void)setMessage:(NSString *)message" insert the following code: self.messageLabel.text = message;

Thanks for the amazing library!! Really like it!!

**Comment by planetexpress69** [comment]
Wont fix.
